version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
    timezone: US/Eastern
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-page-utils
    versions:
    - 0.6.1
    - 0.8.0
  - dependency-name: gatsby-plugin-catch-links
    versions:
    - 2.7.0
  - dependency-name: gatsby-plugin-emotion
    versions:
    - 4.3.10
  - dependency-name: "@mdx-js/react"
    versions:
    - 1.6.6
  - dependency-name: fs-extra
    versions:
    - 9.0.1
  - dependency-name: chalk
    versions:
    - 4.0.0
